# Generated by Django 5.2.6 on 2025-09-23 23:05

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True)),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('common_locations', models.JSONField(default=list)),
                ('common_skills', models.JSONField(default=list)),
                ('common_rate_ranges', models.JSONField(default=list)),
                ('last_searched', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Popular Search',
                'verbose_name_plural': 'Popular Searches',
                'db_table': 'popular_search',
                'ordering': ['-search_count', '-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('search_keywords', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='search.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'db_table': 'skill_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=500)),
                ('filters', models.JSONField(default=dict)),
                ('email_alerts', models.BooleanField(default=False)),
                ('alert_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'db_table': 'saved_search',
                'ordering': ['-last_used'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=500)),
                ('filters_applied', models.JSONField(default=dict)),
                ('results_count', models.PositiveIntegerField()),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('clicked_results', models.JSONField(default=list)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Analytics',
                'verbose_name_plural': 'Search Analytics',
                'db_table': 'search_analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', 'created_at'], name='search_anal_query_2667a1_idx'), models.Index(fields=['user', 'created_at'], name='search_anal_user_id_5f3483_idx'), models.Index(fields=['country', 'city'], name='search_anal_country_459d2f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('skills_text', models.TextField(blank=True)),
                ('skills_list', models.JSONField(default=list)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('hourly_rate_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hourly_rate_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('total_completed_jobs', models.PositiveIntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('search_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Profile',
                'verbose_name_plural': 'Search Profiles',
                'db_table': 'search_profile',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_prof_search__83f016_gin'), models.Index(fields=['is_available', 'search_score'], name='search_prof_is_avai_a4c600_idx'), models.Index(fields=['location', 'is_available'], name='search_prof_locatio_3b1af9_idx'), models.Index(fields=['hourly_rate_min', 'hourly_rate_max'], name='search_prof_hourly__06ab6c_idx'), models.Index(fields=['average_rating', 'total_ratings'], name='search_prof_average_1324d5_idx')],
            },
        ),
    ]
