# Generated by Django 5.2.6 on 2025-09-23 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body_snapshot', models.TextField()),
                ('body_checksum', models.CharField(editable=False, max_length=64)),
                ('file', models.FileField(blank=True, upload_to='contracts/files/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signatures', 'Pending Signatures'), ('fully_signed', 'Fully Signed'), ('void', 'Void'), ('expired', 'Expired')], db_index=True, default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contracts', to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contracts.contract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='contract_templates/')),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.contracttemplate'),
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('company', 'Company'), ('talent', 'Talent'), ('witness', 'Witness'), ('system', 'System')], max_length=20)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('signature_type', models.CharField(choices=[('typed', 'Typed'), ('uploaded', 'Uploaded'), ('drawn', 'Drawn'), ('system', 'System')], max_length=10)),
                ('signature_image', models.FileField(blank=True, upload_to='contracts/signatures/')),
                ('signature_hash', models.CharField(editable=False, max_length=128)),
                ('is_valid', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.contract')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['signed_at'],
                'unique_together': {('contract', 'signer')},
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'status'], name='contracts_c_company_a233d3_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['talent', 'status'], name='contracts_c_talent__427d36_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['body_checksum'], name='contracts_c_body_ch_3141f0_idx'),
        ),
    ]
