# Generated by Django 5.2.6 on 2025-09-23 23:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rater_type', models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer')], max_length=10)),
                ('overall_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_title', models.CharField(blank=True, max_length=200)),
                ('review_text', models.TextField()),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('would_work_again', models.BooleanField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('response_text', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='bookings.booking')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'rating',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('spam', 'Spam'), ('fake', 'Fake Review'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=15)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('upheld', 'Upheld')], default='pending', max_length=10)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('flagger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_flags', to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='ratings.rating')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_flags_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating Flag',
                'verbose_name_plural': 'Rating Flags',
                'db_table': 'rating_flag',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('five_star_count', models.PositiveIntegerField(default=0)),
                ('four_star_count', models.PositiveIntegerField(default=0)),
                ('three_star_count', models.PositiveIntegerField(default=0)),
                ('two_star_count', models.PositiveIntegerField(default=0)),
                ('one_star_count', models.PositiveIntegerField(default=0)),
                ('avg_communication', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('avg_quality', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('avg_timeliness', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('avg_professionalism', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_recommendations', models.PositiveIntegerField(default=0)),
                ('recommendation_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating Statistics',
                'verbose_name_plural': 'Rating Statistics',
                'db_table': 'rating_statistics',
            },
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_user', 'is_public'], name='rating_rated_u_f63067_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['overall_rating', 'created_at'], name='rating_overall_1baa90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('booking', 'rater')},
        ),
        migrations.AlterUniqueTogether(
            name='ratingflag',
            unique_together={('rating', 'flagger')},
        ),
    ]
